# This dockerfile is meant to serve as a rocm base image.
# Add rocm-lib package to rocm/dev-ubuntu-20.04 image

ARG OS_VARIANT
ARG ROCM_VERSION=7.1

FROM rocm/dev-${OS_VARIANT}:${ROCM_VERSION}-hip
ARG GFX_ARCH

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  rocm-ml-libraries \
  && apt-mark auto rocm-hip-libraries
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  miopen-hip-${GFX_ARCH}kdb \
  || true
RUN apt-get clean \
  && rm -rf /var/lib/apt/lists/*
