# This dockerfile is meant to serve as a rocm base image.
# It registers the debian rocm package repository, and installs the rocm-language-runtime package.

FROM ubuntu:24.04

# Register the ROCM package repository, and install rocm-dev package
ARG ROCM_VERSION=6.2
ARG AMDGPU_VERSION=6.2

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates curl \
  && curl -sL https://repo.radeon.com/rocm/rocm.gpg.key >/etc/apt/keyrings/rocm.asc \
  && echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.asc] https://repo.radeon.com/rocm/apt/$ROCM_VERSION noble main" >/etc/apt/sources.list.d/rocm.list \
  && DEBIAN_FRONTEND=noninteractive apt-get purge -y curl \
  && DEBIAN_FRONTEND=noninteractive apt-get --purge -y autoremove
COPY rocm-pin-600 /etc/apt/preferences.d/

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  sudo \
  libelf1t64 \
  kmod \
  file \
  python3 \
  rocm-language-runtime \
  rocminfo \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
